[workspace]
members = ["crates/rava-core", "crates/rava-cli", "crates/rava-wasm"]
exclude = ["fuzz"]
resolver = "2"

[workspace.package]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/syndicalt/rava"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
